version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ../laravel_app:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel_network

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - 9898:80  # Change this line to expose port 9898
    volumes:
      - ../laravel_app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 9899:80  # phpMyAdmin accessible at http://localhost:9899
    networks:
      - laravel_network
    depends_on:
      - db

networks:
  laravel_network:

volumes:
  dbdata:
